# Generated by Django 2.2 on 2019-04-08 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_auto_20190407_1007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='bill_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'New subscription'), (2, 'New agents'), (3, 'Extra tasks')], default=1),
        ),
        migrations.AlterField(
            model_name='payment',
            name='currency',
            field=models.PositiveSmallIntegerField(choices=[(3, 'EUR'), (2, 'USD'), (1, 'BDT')], default=1),
        ),
        migrations.AlterField(
            model_name='payment',
            name='gateway',
            field=models.PositiveSmallIntegerField(choices=[(2, 'SSL'), (1, 'BKASH'), (3, 'IPAY')], default=1),
        ),
        migrations.AlterField(
            model_name='payment',
            name='package',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Attendance'), (0, 'None'), (2, 'Tracking'), (3, 'Full Suite')], default=0),
        ),
        migrations.AlterField(
            model_name='payment',
            name='state',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Created'), (2, 'Successful'), (0, 'Initiated')], default=0),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='currency',
            field=models.PositiveSmallIntegerField(choices=[(3, 'EUR'), (2, 'USD'), (1, 'BDT')], default=1),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='package',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Attendance'), (0, 'None'), (2, 'Tracking'), (3, 'Full Suite')], default=0),
        ),
        migrations.AlterField(
            model_name='usage',
            name='package',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Attendance'), (0, 'None'), (2, 'Tracking'), (3, 'Full Suite')], default=0),
        ),
        migrations.AlterField(
            model_name='usage',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(3, 'suspended'), (2, 'expired'), (1, 'active')], default=1),
        ),
    ]
