# Generated by Django 2.2 on 2019-04-08 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_auto_20190408_0646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='bill_type',
            field=models.PositiveSmallIntegerField(choices=[(3, 'Extra tasks'), (1, 'New subscription'), (2, 'New agents')], default=1),
        ),
        migrations.AlterField(
            model_name='payment',
            name='gateway',
            field=models.PositiveSmallIntegerField(choices=[(1, 'BKASH'), (3, 'IPAY'), (2, 'SSL')], default=1),
        ),
        migrations.AlterField(
            model_name='payment',
            name='package',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Attendance'), (0, 'None'), (3, 'Full Suite'), (2, 'Tracking')], default=0),
        ),
        migrations.AlterField(
            model_name='payment',
            name='state',
            field=models.PositiveSmallIntegerField(choices=[(2, 'Successful'), (0, 'Initiated'), (1, 'Created')], default=0),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='package',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Attendance'), (0, 'None'), (3, 'Full Suite'), (2, 'Tracking')], default=0),
        ),
        migrations.AlterField(
            model_name='usage',
            name='package',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Attendance'), (0, 'None'), (3, 'Full Suite'), (2, 'Tracking')], default=0),
        ),
    ]
