# Generated by Django 2.2 on 2019-05-05 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0009_auto_20190502_0455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='bill_type',
            field=models.PositiveSmallIntegerField(choices=[(2, 'New agents'), (3, 'Extra tasks'), (1, 'New subscription')], default=1),
        ),
        migrations.AlterField(
            model_name='payment',
            name='currency',
            field=models.PositiveSmallIntegerField(choices=[(3, 'EUR'), (2, 'USD'), (1, 'BDT')], default=1),
        ),
        migrations.AlterField(
            model_name='payment',
            name='gateway',
            field=models.PositiveSmallIntegerField(choices=[(1, 'BKASH'), (3, 'IPAY'), (2, 'SSL')], default=1),
        ),
        migrations.AlterField(
            model_name='payment',
            name='package',
            field=models.PositiveSmallIntegerField(choices=[(2, 'Tracking'), (0, 'None'), (1, 'Attendance'), (3, 'Full Suite')], default=0),
        ),
        migrations.AlterField(
            model_name='payment',
            name='state',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Created'), (0, 'Initiated'), (2, 'Successful')], default=0),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='currency',
            field=models.PositiveSmallIntegerField(choices=[(3, 'EUR'), (2, 'USD'), (1, 'BDT')], default=1),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='package',
            field=models.PositiveSmallIntegerField(choices=[(2, 'Tracking'), (0, 'None'), (1, 'Attendance'), (3, 'Full Suite')], default=0),
        ),
        migrations.AlterField(
            model_name='usage',
            name='package',
            field=models.PositiveSmallIntegerField(choices=[(2, 'Tracking'), (0, 'None'), (1, 'Attendance'), (3, 'Full Suite')], default=0),
        ),
        migrations.AlterField(
            model_name='usage',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'active'), (3, 'suspended'), (2, 'expired')], default=1),
        ),
    ]
