# Generated by Django 2.2 on 2019-05-22 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0015_auto_20190522_0449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='bill_type',
            field=models.PositiveSmallIntegerField(choices=[(3, 'Extra tasks'), (2, 'New agents'), (1, 'New subscription')], default=1),
        ),
        migrations.AlterField(
            model_name='payment',
            name='currency',
            field=models.PositiveSmallIntegerField(choices=[(3, 'EUR'), (1, 'BDT'), (2, 'USD')], default=1),
        ),
        migrations.AlterField(
            model_name='payment',
            name='gateway',
            field=models.PositiveSmallIntegerField(choices=[(2, 'SSL'), (1, 'BKASH'), (3, 'IPAY')], default=1),
        ),
        migrations.AlterField(
            model_name='payment',
            name='package',
            field=models.PositiveSmallIntegerField(choices=[(2, 'Tracking'), (0, 'None'), (4, 'Task Management'), (1, 'Attendance'), (3, 'Full Suite')], default=0),
        ),
        migrations.AlterField(
            model_name='payment',
            name='state',
            field=models.PositiveSmallIntegerField(choices=[(2, 'Successful'), (1, 'Created'), (0, 'Initiated')], default=0),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='currency',
            field=models.PositiveSmallIntegerField(choices=[(3, 'EUR'), (1, 'BDT'), (2, 'USD')], default=1),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='package',
            field=models.PositiveSmallIntegerField(choices=[(2, 'Tracking'), (0, 'None'), (4, 'Task Management'), (1, 'Attendance'), (3, 'Full Suite')], default=0),
        ),
        migrations.AlterField(
            model_name='usage',
            name='package',
            field=models.PositiveSmallIntegerField(choices=[(2, 'Tracking'), (0, 'None'), (4, 'Task Management'), (1, 'Attendance'), (3, 'Full Suite')], default=0),
        ),
        migrations.AlterField(
            model_name='usage',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(2, 'expired'), (3, 'suspended'), (1, 'active')], default=1),
        ),
    ]
