# Generated by Django 2.2 on 2019-05-27 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0018_auto_20190525_0934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='currency',
            field=models.PositiveSmallIntegerField(choices=[(1, 'BDT'), (3, 'EUR'), (2, 'USD')], default=1),
        ),
        migrations.AlterField(
            model_name='payment',
            name='gateway',
            field=models.PositiveSmallIntegerField(choices=[(1, 'BKASH'), (3, 'IPAY'), (2, 'SSL')], default=1),
        ),
        migrations.AlterField(
            model_name='payment',
            name='package',
            field=models.PositiveSmallIntegerField(choices=[(3, 'Full Suite'), (1, 'Attendance'), (0, 'None'), (2, 'Tracking'), (4, 'Task Management')], default=0),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='currency',
            field=models.PositiveSmallIntegerField(choices=[(1, 'BDT'), (3, 'EUR'), (2, 'USD')], default=1),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='package',
            field=models.PositiveSmallIntegerField(choices=[(3, 'Full Suite'), (1, 'Attendance'), (0, 'None'), (2, 'Tracking'), (4, 'Task Management')], default=0),
        ),
        migrations.AlterField(
            model_name='usage',
            name='package',
            field=models.PositiveSmallIntegerField(choices=[(3, 'Full Suite'), (1, 'Attendance'), (0, 'None'), (2, 'Tracking'), (4, 'Task Management')], default=0),
        ),
        migrations.AlterField(
            model_name='usage',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'active'), (2, 'expired'), (3, 'suspended')], default=1),
        ),
    ]
