# Generated by Django 2.2 on 2019-06-09 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0020_auto_20190609_0939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='bill_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'New subscription'), (3, 'Extra tasks'), (2, 'New agents')], default=1),
        ),
        migrations.AlterField(
            model_name='payment',
            name='gateway',
            field=models.PositiveSmallIntegerField(choices=[(3, 'IPAY'), (1, 'BKASH'), (2, 'SSL')], default=1),
        ),
        migrations.AlterField(
            model_name='payment',
            name='package',
            field=models.PositiveSmallIntegerField(choices=[(0, 'None'), (3, 'Full Suite'), (2, 'Tracking'), (1, 'Attendance'), (4, 'Task Management')], default=0),
        ),
        migrations.AlterField(
            model_name='payment',
            name='state',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Initiated'), (1, 'Created'), (2, 'Successful')], default=0),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='package',
            field=models.PositiveSmallIntegerField(choices=[(0, 'None'), (3, 'Full Suite'), (2, 'Tracking'), (1, 'Attendance'), (4, 'Task Management')], default=0),
        ),
        migrations.AlterField(
            model_name='usage',
            name='package',
            field=models.PositiveSmallIntegerField(choices=[(0, 'None'), (3, 'Full Suite'), (2, 'Tracking'), (1, 'Attendance'), (4, 'Task Management')], default=0),
        ),
        migrations.AlterField(
            model_name='usage',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(2, 'expired'), (3, 'suspended'), (1, 'active')], default=1),
        ),
    ]
