# Generated by Django 2.2 on 2019-06-19 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0022_auto_20190609_1050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='currency',
            field=models.PositiveSmallIntegerField(choices=[(2, 'USD'), (3, 'EUR'), (1, 'BDT')], default=1),
        ),
        migrations.AlterField(
            model_name='payment',
            name='package',
            field=models.PositiveSmallIntegerField(choices=[(3, 'Full Suite'), (2, 'Tracking'), (4, 'Task Management'), (1, 'Attendance'), (0, 'None')], default=0),
        ),
        migrations.AlterField(
            model_name='payment',
            name='state',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Initiated'), (2, 'Successful'), (1, 'Created')], default=0),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='currency',
            field=models.PositiveSmallIntegerField(choices=[(2, 'USD'), (3, 'EUR'), (1, 'BDT')], default=1),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='package',
            field=models.PositiveSmallIntegerField(choices=[(3, 'Full Suite'), (2, 'Tracking'), (4, 'Task Management'), (1, 'Attendance'), (0, 'None')], default=0),
        ),
        migrations.AlterField(
            model_name='usage',
            name='package',
            field=models.PositiveSmallIntegerField(choices=[(3, 'Full Suite'), (2, 'Tracking'), (4, 'Task Management'), (1, 'Attendance'), (0, 'None')], default=0),
        ),
        migrations.AlterField(
            model_name='usage',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'active'), (3, 'suspended'), (2, 'expired')], default=1),
        ),
    ]
