# Generated by Django 2.2 on 2019-04-07 03:10

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceCombined',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('date', models.DateField(default=datetime.date.today)),
            ],
            options={
                'verbose_name_plural': 'Combined Attendance Reports',
                'verbose_name': 'Combined Attendance Report',
            },
        ),
        migrations.CreateModel(
            name='AttendanceIndividual',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('status', models.PositiveSmallIntegerField(choices=[(3, 'Holiday'), (4, 'On Leave'), (1, 'Present'), (0, 'Absent'), (2, 'Weekend')], default=0)),
                ('init_entry_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_entry_time', models.DateTimeField(blank=True, null=True)),
                ('late_arrival', models.BooleanField(default=False)),
                ('exit_time', models.DateTimeField(blank=True, null=True)),
                ('work_hour', models.DurationField(blank=True, null=True)),
                ('task_hour', models.DurationField(blank=True, null=True)),
                ('task_hour_p', models.FloatField(blank=True, default=0.0)),
                ('travel_distance', models.PositiveIntegerField(blank=True, default=0)),
            ],
            options={
                'verbose_name_plural': 'Individual Attendance Reports',
                'verbose_name': 'Individual Attendance Report',
            },
        ),
        migrations.CreateModel(
            name='Ranking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('date_range', models.PositiveSmallIntegerField(choices=[(3, 'last_week'), (5, 'last_month'), (1, 'last_day'), (2, 'this_week'), (4, 'this_month')], default=2)),
                ('absence', models.PositiveIntegerField(default=0)),
                ('low_task_hour', models.PositiveIntegerField(default=0)),
                ('low_work_hour', models.PositiveIntegerField(default=0)),
                ('overtime', models.PositiveIntegerField(default=0)),
                ('late_arrival', models.PositiveIntegerField(default=0)),
                ('delayed_task', models.PositiveIntegerField(default=0)),
                ('travel_distance', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Rankings',
                'verbose_name': 'Ranking',
            },
        ),
        migrations.CreateModel(
            name='TaskCombined',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('date', models.DateField(default=datetime.date.today)),
            ],
            options={
                'verbose_name_plural': 'Task Reports',
                'verbose_name': 'Task Report',
            },
        ),
    ]
