# Generated by Django 2.2 on 2019-04-07 03:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('report', '0002_auto_20190407_0310'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('org', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ranking',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='attendanceindividual',
            name='org',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='org.Organization'),
        ),
        migrations.AddField(
            model_name='attendanceindividual',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='attendancecombined',
            name='absent',
            field=models.ManyToManyField(blank=True, related_name='user_absent', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='attendancecombined',
            name='late_arrival',
            field=models.ManyToManyField(blank=True, related_name='user_late_arrival', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='attendancecombined',
            name='low_task_hour',
            field=models.ManyToManyField(blank=True, related_name='user_low_task_hour', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='attendancecombined',
            name='low_work_hour',
            field=models.ManyToManyField(blank=True, related_name='user_low_work_hour', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='attendancecombined',
            name='org',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='org.Organization'),
        ),
        migrations.AddField(
            model_name='attendancecombined',
            name='overtime',
            field=models.ManyToManyField(blank=True, related_name='user_overtime', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='attendancecombined',
            name='present',
            field=models.ManyToManyField(blank=True, related_name='user_present', to=settings.AUTH_USER_MODEL),
        ),
    ]
