# Generated by Django 2.2 on 2019-04-08 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0004_auto_20190407_1007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendanceindividual',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(4, 'On Leave'), (3, 'Holiday'), (1, 'Present'), (2, 'Weekend'), (0, 'Absent')], default=0),
        ),
        migrations.AlterField(
            model_name='ranking',
            name='date_range',
            field=models.PositiveSmallIntegerField(choices=[(5, 'last_month'), (3, 'last_week'), (4, 'this_month'), (2, 'this_week'), (1, 'last_day')], default=2),
        ),
    ]
