# Generated by Django 2.2 on 2019-04-08 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0006_auto_20190408_0646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendanceindividual',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Present'), (0, 'Absent'), (2, 'Weekend'), (4, 'On Leave'), (3, 'Holiday')], default=0),
        ),
        migrations.AlterField(
            model_name='ranking',
            name='date_range',
            field=models.PositiveSmallIntegerField(choices=[(3, 'last_week'), (4, 'this_month'), (5, 'last_month'), (1, 'last_day'), (2, 'this_week')], default=2),
        ),
    ]
