# Generated by Django 2.2 on 2019-04-11 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0007_auto_20190408_0925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendanceindividual',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Absent'), (4, 'On Leave'), (3, 'Holiday'), (1, 'Present'), (2, 'Weekend')], default=0),
        ),
        migrations.AlterField(
            model_name='ranking',
            name='date_range',
            field=models.PositiveSmallIntegerField(choices=[(1, 'last_day'), (5, 'last_month'), (4, 'this_month'), (3, 'last_week'), (2, 'this_week')], default=2),
        ),
    ]
