# Generated by Django 2.2 on 2019-04-15 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0008_auto_20190411_0944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendanceindividual',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(3, 'Holiday'), (4, 'On Leave'), (1, 'Present'), (0, 'Absent'), (2, 'Weekend')], default=0),
        ),
        migrations.AlterField(
            model_name='ranking',
            name='date_range',
            field=models.PositiveSmallIntegerField(choices=[(3, 'last_week'), (2, 'this_week'), (1, 'last_day'), (4, 'this_month'), (5, 'last_month')], default=2),
        ),
    ]
