# Generated by Django 2.2 on 2019-04-23 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0009_auto_20190415_0641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendanceindividual',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(3, 'Holiday'), (2, 'Weekend'), (0, 'Absent'), (1, 'Present'), (4, 'On Leave')], default=0),
        ),
        migrations.AlterField(
            model_name='ranking',
            name='date_range',
            field=models.PositiveSmallIntegerField(choices=[(2, 'this_week'), (4, 'this_month'), (1, 'last_day'), (5, 'last_month'), (3, 'last_week')], default=2),
        ),
    ]
