# Generated by Django 2.2 on 2019-05-02 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0010_auto_20190423_0627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendanceindividual',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(3, 'Holiday'), (1, 'Present'), (0, 'Absent'), (2, 'Weekend'), (4, 'On Leave')], default=0),
        ),
        migrations.AlterField(
            model_name='ranking',
            name='date_range',
            field=models.PositiveSmallIntegerField(choices=[(5, 'last_month'), (2, 'this_week'), (3, 'last_week'), (4, 'this_month'), (1, 'last_day')], default=2),
        ),
    ]
