# Generated by Django 2.2 on 2019-05-05 11:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0011_auto_20190502_0455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancecombined',
            name='date',
            field=models.DateField(db_index=True, default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='attendanceindividual',
            name='date',
            field=models.DateField(db_index=True, default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='attendanceindividual',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(2, 'Weekend'), (4, 'On Leave'), (3, 'Holiday'), (1, 'Present'), (0, 'Absent')], default=0),
        ),
        migrations.AlterField(
            model_name='ranking',
            name='date',
            field=models.DateField(db_index=True, default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='ranking',
            name='date_range',
            field=models.PositiveSmallIntegerField(choices=[(5, 'last_month'), (2, 'this_week'), (4, 'this_month'), (1, 'last_day'), (3, 'last_week')], default=2),
        ),
        migrations.AlterField(
            model_name='taskcombined',
            name='date',
            field=models.DateField(db_index=True, default=datetime.date.today),
        ),
    ]
