# Generated by Django 2.2 on 2019-05-05 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0012_auto_20190505_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendanceindividual',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Absent'), (1, 'Present'), (3, 'Holiday'), (4, 'On Leave'), (2, 'Weekend')], default=0),
        ),
        migrations.AlterField(
            model_name='ranking',
            name='date_range',
            field=models.PositiveSmallIntegerField(choices=[(1, 'last_day'), (3, 'last_week'), (5, 'last_month'), (4, 'this_month'), (2, 'this_week')], default=2),
        ),
    ]
