# Generated by Django 2.2 on 2019-05-13 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0013_auto_20190505_1213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendanceindividual',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(2, 'Weekend'), (1, 'Present'), (0, 'Absent'), (3, 'Holiday'), (4, 'On Leave')], default=0),
        ),
        migrations.AlterField(
            model_name='ranking',
            name='date_range',
            field=models.PositiveSmallIntegerField(choices=[(5, 'last_month'), (2, 'this_week'), (1, 'last_day'), (3, 'last_week'), (4, 'this_month')], default=2),
        ),
    ]
