# Generated by Django 2.2 on 2019-05-16 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0014_auto_20190513_0517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendanceindividual',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(2, 'Weekend'), (1, 'Present'), (4, 'On Leave'), (3, 'Holiday'), (0, 'Absent')], default=0),
        ),
        migrations.AlterField(
            model_name='ranking',
            name='date_range',
            field=models.PositiveSmallIntegerField(choices=[(1, 'last_day'), (5, 'last_month'), (2, 'this_week'), (3, 'last_week'), (4, 'this_month')], default=2),
        ),
    ]
