# Generated by Django 2.2 on 2019-05-22 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0016_auto_20190520_0822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendanceindividual',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(3, 'Holiday'), (4, 'On Leave'), (2, 'Weekend'), (0, 'Absent'), (1, 'Present')], default=0),
        ),
        migrations.AlterField(
            model_name='ranking',
            name='date_range',
            field=models.PositiveSmallIntegerField(choices=[(1, 'last_day'), (2, 'this_week'), (3, 'last_week'), (4, 'this_month'), (5, 'last_month')], default=2),
        ),
    ]
