# Generated by Django 2.2 on 2019-05-25 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0018_auto_20190522_0934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendanceindividual',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Present'), (2, 'Weekend'), (0, 'Absent'), (4, 'On Leave'), (3, 'Holiday')], default=0),
        ),
        migrations.AlterField(
            model_name='ranking',
            name='date_range',
            field=models.PositiveSmallIntegerField(choices=[(3, 'last_week'), (4, 'this_month'), (1, 'last_day'), (5, 'last_month'), (2, 'this_week')], default=2),
        ),
    ]
