# Generated by Django 2.2 on 2019-05-25 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0019_auto_20190525_0739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendanceindividual',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(3, 'Holiday'), (4, 'On Leave'), (0, 'Absent'), (2, 'Weekend'), (1, 'Present')], default=0),
        ),
        migrations.AlterField(
            model_name='ranking',
            name='date_range',
            field=models.PositiveSmallIntegerField(choices=[(4, 'this_month'), (5, 'last_month'), (3, 'last_week'), (1, 'last_day'), (2, 'this_week')], default=2),
        ),
    ]
