# Generated by Django 2.2 on 2019-05-27 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0020_auto_20190525_0934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendanceindividual',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(3, 'Holiday'), (4, 'On Leave'), (1, 'Present'), (0, 'Absent'), (2, 'Weekend')], default=0),
        ),
        migrations.AlterField(
            model_name='ranking',
            name='date_range',
            field=models.PositiveSmallIntegerField(choices=[(2, 'this_week'), (4, 'this_month'), (5, 'last_month'), (1, 'last_day'), (3, 'last_week')], default=2),
        ),
    ]
