# Generated by Django 2.2 on 2019-06-09 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0022_auto_20190609_0939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendanceindividual',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Present'), (2, 'Weekend'), (3, 'Holiday'), (4, 'On Leave'), (0, 'Absent')], default=0),
        ),
        migrations.AlterField(
            model_name='ranking',
            name='date_range',
            field=models.PositiveSmallIntegerField(choices=[(5, 'last_month'), (3, 'last_week'), (2, 'this_week'), (4, 'this_month'), (1, 'last_day')], default=2),
        ),
    ]
