# Generated by Django 2.2 on 2019-06-09 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0023_auto_20190609_0954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendanceindividual',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(2, 'Weekend'), (3, 'Holiday'), (0, 'Absent'), (1, 'Present'), (4, 'On Leave')], default=0),
        ),
        migrations.AlterField(
            model_name='ranking',
            name='date_range',
            field=models.PositiveSmallIntegerField(choices=[(5, 'last_month'), (3, 'last_week'), (1, 'last_day'), (4, 'this_month'), (2, 'this_week')], default=2),
        ),
    ]
