# Generated by Django 2.2 on 2019-07-04 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0025_auto_20190619_0449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendanceindividual',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Present'), (0, 'Absent'), (3, 'Holiday'), (4, 'On Leave'), (2, 'Weekend')], default=0),
        ),
        migrations.AlterField(
            model_name='ranking',
            name='date_range',
            field=models.PositiveSmallIntegerField(choices=[(2, 'this_week'), (1, 'last_day'), (4, 'this_month'), (5, 'last_month'), (3, 'last_week')], default=2),
        ),
    ]
