# Generated by Django 2.2 on 2019-07-17 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0026_auto_20190704_0508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendanceindividual',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Present'), (4, 'On Leave'), (0, 'Absent'), (3, 'Holiday'), (2, 'Weekend')], default=0),
        ),
        migrations.AlterField(
            model_name='ranking',
            name='date_range',
            field=models.PositiveSmallIntegerField(choices=[(4, 'this_month'), (3, 'last_week'), (5, 'last_month'), (2, 'this_week'), (1, 'last_day')], default=2),
        ),
    ]
