# Generated by Django 2.2 on 2019-07-24 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0027_auto_20190717_1230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendanceindividual',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Absent'), (2, 'Weekend'), (3, 'Holiday'), (4, 'On Leave'), (1, 'Present')], default=0),
        ),
        migrations.AlterField(
            model_name='ranking',
            name='date_range',
            field=models.PositiveSmallIntegerField(choices=[(3, 'last_week'), (4, 'this_month'), (2, 'this_week'), (1, 'last_day'), (5, 'last_month')], default=2),
        ),
    ]
