# Generated by Django 2.2 on 2019-04-15 06:41

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('state', '0003_userstate_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userstate',
            name='is_awol',
        ),
        migrations.RemoveField(
            model_name='userstate',
            name='is_present',
        ),
        migrations.CreateModel(
            name='DeviceHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mac', models.CharField(blank=True, max_length=255, null=True)),
                ('model_no', models.CharField(blank=True, max_length=255, null=True)),
                ('date', models.DateField(default=datetime.date.today)),
                ('timestamp', models.DateField(default=datetime.datetime.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='userstate',
            name='current_device',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='state.DeviceHistory'),
        ),
    ]
