# Generated by Django 2.2 on 2019-05-02 04:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('state', '0004_auto_20190415_0641'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstate',
            name='fb_token',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userstate',
            name='is_awol',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userstate',
            name='is_present',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userstate',
            name='is_working',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='userstate',
            name='current_device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='state.DeviceHistory'),
        ),
    ]
