# Generated by Django 2.2 on 2019-05-27 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('state', '0005_auto_20190502_0455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicehistory',
            name='mac',
            field=models.CharField(blank=True, default='', max_length=64, null=True),
        ),
    ]
