# Generated by Django 2.2 on 2019-04-07 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_auto_20190407_0310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Remaining'), (0, 'Unassigned'), (4, 'Cancelled'), (5, 'Postponed'), (2, 'In progress'), (3, 'Complete')], default=0),
        ),
    ]
