# Generated by Django 2.2 on 2019-04-08 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0004_auto_20190408_0518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Remaining'), (5, 'Postponed'), (3, 'Complete'), (2, 'In progress'), (4, 'Cancelled'), (0, 'Unassigned')], default=0),
        ),
    ]
