# Generated by Django 2.2 on 2019-04-08 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0005_auto_20190408_0646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Remaining'), (0, 'Unassigned'), (5, 'Postponed'), (4, 'Cancelled'), (3, 'Complete'), (2, 'In progress')], default=0),
        ),
    ]
