# Generated by Django 2.2 on 2019-04-15 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0007_auto_20190411_0944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(2, 'In progress'), (4, 'Cancelled'), (0, 'Unassigned'), (3, 'Complete'), (1, 'Remaining'), (5, 'Postponed')], default=0),
        ),
    ]
