# Generated by Django 2.2 on 2019-04-23 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0008_auto_20190415_0641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Unassigned'), (4, 'Cancelled'), (1, 'Remaining'), (2, 'In progress'), (5, 'Postponed'), (3, 'Complete')], default=0),
        ),
    ]
