# Generated by Django 2.2 on 2019-05-02 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0009_auto_20190423_0627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Unassigned'), (1, 'Remaining'), (4, 'Cancelled'), (5, 'Postponed'), (2, 'In progress'), (3, 'Complete')], default=0),
        ),
    ]
