# Generated by Django 2.2 on 2019-05-05 11:54

import apps.task.config
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0010_auto_20190502_0455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='date',
            field=models.DateField(db_index=True, default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='task',
            name='deadline',
            field=models.DateTimeField(db_index=True, default=apps.task.config.default_duration),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Remaining'), (4, 'Cancelled'), (3, 'Complete'), (0, 'Unassigned'), (5, 'Postponed'), (2, 'In progress')], default=0),
        ),
    ]
