# Generated by Django 2.2 on 2019-05-05 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0011_auto_20190505_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(5, 'Postponed'), (1, 'Remaining'), (2, 'In progress'), (4, 'Cancelled'), (3, 'Complete'), (0, 'Unassigned')], default=0),
        ),
    ]
