# Generated by Django 2.2 on 2019-05-13 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0012_auto_20190505_1213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(2, 'In progress'), (0, 'Unassigned'), (4, 'Cancelled'), (3, 'Complete'), (1, 'Remaining'), (5, 'Postponed')], default=0),
        ),
    ]
