# Generated by Django 2.2 on 2019-05-22 04:49

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0015_auto_20190520_0822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='custom_fields',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Unassigned'), (4, 'Cancelled'), (3, 'Complete'), (5, 'Postponed'), (1, 'Remaining'), (2, 'In progress')], default=0),
        ),
    ]
