# Generated by Django 2.2 on 2019-05-22 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0016_auto_20190522_0449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(2, 'In progress'), (3, 'Complete'), (5, 'Postponed'), (0, 'Unassigned'), (4, 'Cancelled'), (1, 'Remaining')], default=0),
        ),
    ]
