# Generated by Django 2.2 on 2019-05-25 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0017_auto_20190522_0934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(5, 'Postponed'), (2, 'In progress'), (3, 'Complete'), (1, 'Remaining'), (4, 'Cancelled'), (0, 'Unassigned')], default=0),
        ),
    ]
