# Generated by Django 2.2 on 2019-05-25 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0018_auto_20190525_0739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(3, 'Complete'), (1, 'Remaining'), (5, 'Postponed'), (0, 'Unassigned'), (2, 'In progress'), (4, 'Cancelled')], default=0),
        ),
    ]
