# Generated by Django 2.2 on 2019-05-27 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0019_auto_20190525_0934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(5, 'Postponed'), (1, 'Remaining'), (0, 'Unassigned'), (2, 'In progress'), (3, 'Complete'), (4, 'Cancelled')], default=0),
        ),
    ]
