# Generated by Django 2.2 on 2019-06-09 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0020_auto_20190527_0406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Remaining'), (4, 'Cancelled'), (5, 'Postponed'), (2, 'In progress'), (0, 'Unassigned'), (3, 'Complete')], default=0),
        ),
    ]
