# Generated by Django 2.2 on 2019-06-09 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0021_auto_20190609_0939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Unassigned'), (4, 'Cancelled'), (2, 'In progress'), (1, 'Remaining'), (3, 'Complete'), (5, 'Postponed')], default=0),
        ),
    ]
