# Generated by Django 2.2 on 2019-06-09 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0022_auto_20190609_0954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(4, 'Cancelled'), (1, 'Remaining'), (0, 'Unassigned'), (3, 'Complete'), (2, 'In progress'), (5, 'Postponed')], default=0),
        ),
    ]
