# Generated by Django 2.2 on 2019-07-04 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0024_auto_20190619_0449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(4, 'Cancelled'), (1, 'Remaining'), (2, 'In progress'), (0, 'Unassigned'), (5, 'Postponed'), (3, 'Complete')], default=0),
        ),
    ]
