# Generated by Django 2.2 on 2019-07-17 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0025_auto_20190704_0508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Remaining'), (0, 'Unassigned'), (3, 'Complete'), (4, 'Cancelled'), (2, 'In progress'), (5, 'Postponed')], default=0),
        ),
    ]
