# Generated by Django 2.2 on 2019-07-24 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0026_auto_20190717_1230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Remaining'), (5, 'Postponed'), (4, 'Cancelled'), (2, 'In progress'), (0, 'Unassigned'), (3, 'Complete')], default=0),
        ),
    ]
