# Generated by Django 2.2 on 2019-04-07 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='domain',
            field=models.PositiveSmallIntegerField(choices=[(5, 'Others'), (3, 'Rent-a-car/Ride sharing'), (6, 'Sales(Pharma)'), (4, 'Insurance'), (2, 'Installation/Maintenance/Repair'), (0, 'Sales'), (1, 'Delivery Service')], default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Manager'), (2, 'Employee'), (0, 'Organizer'), (3, 'Leader')], default=2),
        ),
    ]
