# Generated by Django 2.2 on 2019-04-08 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20190407_1007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='domain',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Sales'), (2, 'Installation/Maintenance/Repair'), (5, 'Others'), (6, 'Sales(Pharma)'), (1, 'Delivery Service'), (4, 'Insurance'), (3, 'Rent-a-car/Ride sharing')], default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(3, 'Leader'), (0, 'Organizer'), (1, 'Manager'), (2, 'Employee')], default=2),
        ),
    ]
