# Generated by Django 2.2 on 2019-04-08 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20190408_0518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='domain',
            field=models.PositiveSmallIntegerField(choices=[(4, 'Insurance'), (5, 'Others'), (0, 'Sales'), (1, 'Delivery Service'), (6, 'Sales(Pharma)'), (3, 'Rent-a-car/Ride sharing'), (2, 'Installation/Maintenance/Repair')], default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Organizer'), (1, 'Manager'), (3, 'Leader'), (2, 'Employee')], default=2),
        ),
    ]
