# Generated by Django 2.2 on 2019-04-08 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20190408_0646'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='active_task',
        ),
        migrations.AddField(
            model_name='user',
            name='is_working',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='domain',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Sales'), (6, 'Sales(Pharma)'), (3, 'Rent-a-car/Ride sharing'), (4, 'Insurance'), (5, 'Others'), (2, 'Installation/Maintenance/Repair'), (1, 'Delivery Service')], default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Organizer'), (2, 'Employee'), (1, 'Manager'), (3, 'Leader')], default=2),
        ),
    ]
