# Generated by Django 2.2 on 2019-04-11 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20190408_0925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='domain',
            field=models.PositiveSmallIntegerField(choices=[(6, 'Sales(Pharma)'), (2, 'Installation/Maintenance/Repair'), (5, 'Others'), (1, 'Delivery Service'), (0, 'Sales'), (4, 'Insurance'), (3, 'Rent-a-car/Ride sharing')], default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(2, 'Employee'), (3, 'Leader'), (1, 'Manager'), (0, 'Organizer')], default=2),
        ),
    ]
