# Generated by Django 2.2 on 2019-04-15 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20190411_0944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='domain',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Delivery Service'), (2, 'Installation/Maintenance/Repair'), (4, 'Insurance'), (5, 'Others'), (0, 'Sales'), (6, 'Sales(Pharma)'), (3, 'Rent-a-car/Ride sharing')], default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='fb_token',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Organizer'), (2, 'Employee'), (1, 'Manager'), (3, 'Leader')], default=2),
        ),
    ]
