# Generated by Django 2.2 on 2019-04-23 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20190415_0641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='domain',
            field=models.PositiveSmallIntegerField(choices=[(4, 'Insurance'), (0, 'Sales'), (6, 'Sales(Pharma)'), (2, 'Installation/Maintenance/Repair'), (5, 'Others'), (1, 'Delivery Service'), (3, 'Rent-a-car/Ride sharing')], default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Manager'), (0, 'Organizer'), (2, 'Employee'), (3, 'Leader')], default=2),
        ),
    ]
