# Generated by Django 2.2 on 2019-05-02 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_auto_20190423_0627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='domain',
            field=models.PositiveSmallIntegerField(choices=[(6, 'Sales(Pharma)'), (5, 'Others'), (3, 'Rent-a-car/Ride sharing'), (1, 'Delivery Service'), (0, 'Sales'), (2, 'Installation/Maintenance/Repair'), (4, 'Insurance')], default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Manager'), (0, 'Organizer'), (3, 'Leader'), (2, 'Employee')], default=2),
        ),
    ]
