# Generated by Django 2.2 on 2019-05-05 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_auto_20190502_0455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='domain',
            field=models.PositiveSmallIntegerField(choices=[(2, 'Installation/Maintenance/Repair'), (0, 'Sales'), (6, 'Sales(Pharma)'), (3, 'Rent-a-car/Ride sharing'), (4, 'Insurance'), (5, 'Others'), (1, 'Delivery Service')], default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Organizer'), (3, 'Leader'), (1, 'Manager'), (2, 'Employee')], default=2),
        ),
    ]
