# Generated by Django 2.2 on 2019-05-05 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_auto_20190505_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='domain',
            field=models.PositiveSmallIntegerField(choices=[(2, 'Installation/Maintenance/Repair'), (6, 'Sales(Pharma)'), (1, 'Delivery Service'), (3, 'Rent-a-car/Ride sharing'), (0, 'Sales'), (5, 'Others'), (4, 'Insurance')], default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Manager'), (0, 'Organizer'), (2, 'Employee'), (3, 'Leader')], default=2),
        ),
    ]
