# Generated by Django 2.2 on 2019-05-16 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_auto_20190513_0517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='domain',
            field=models.PositiveSmallIntegerField(choices=[(6, 'Sales(Pharma)'), (0, 'Sales'), (3, 'Rent-a-car/Ride sharing'), (1, 'Delivery Service'), (5, 'Others'), (4, 'Insurance'), (2, 'Installation/Maintenance/Repair')], default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(3, 'Leader'), (2, 'Employee'), (0, 'Organizer'), (1, 'Manager')], default=2),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, max_length=32, null=True, unique=True),
        ),
    ]
