# Generated by Django 2.2 on 2019-05-20 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_auto_20190516_0613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='domain',
            field=models.PositiveSmallIntegerField(choices=[(2, 'Installation/Maintenance/Repair'), (0, 'Sales'), (4, 'Insurance'), (6, 'Sales(Pharma)'), (3, 'Rent-a-car/Ride sharing'), (5, 'Others'), (1, 'Delivery Service')], default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(3, 'Leader'), (0, 'Organizer'), (1, 'Manager'), (2, 'Employee')], default=2),
        ),
    ]
