# Generated by Django 2.2 on 2019-05-22 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_auto_20190520_0822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='domain',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Delivery Service'), (6, 'Sales(Pharma)'), (2, 'Installation/Maintenance/Repair'), (0, 'Sales'), (4, 'Insurance'), (3, 'Rent-a-car/Ride sharing'), (5, 'Others')], default=0),
        ),
    ]
