# Generated by Django 2.2 on 2019-05-25 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_auto_20190522_0934'),
    ]

    operations = [
        migrations.AddField(
            model_name='datausage',
            name='mac',
            field=models.CharField(blank=True, default='', max_length=16),
        ),
        migrations.AlterField(
            model_name='user',
            name='domain',
            field=models.PositiveSmallIntegerField(choices=[(4, 'Insurance'), (1, 'Delivery Service'), (6, 'Sales(Pharma)'), (2, 'Installation/Maintenance/Repair'), (0, 'Sales'), (3, 'Rent-a-car/Ride sharing'), (5, 'Others')], default=0),
        ),
    ]
