# Generated by Django 2.2 on 2019-06-09 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0019_auto_20190527_0406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='domain',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Sales'), (2, 'Installation/Maintenance/Repair'), (5, 'Others'), (1, 'Delivery Service'), (6, 'Sales(Pharma)'), (3, 'Rent-a-car/Ride sharing'), (4, 'Insurance')], default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Organizer'), (1, 'Manager'), (3, 'Leader'), (2, 'Employee')], default=2),
        ),
    ]
