# Generated by Django 2.2 on 2019-06-09 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0020_auto_20190609_0939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='domain',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Sales'), (1, 'Delivery Service'), (6, 'Sales(Pharma)'), (3, 'Rent-a-car/Ride sharing'), (2, 'Installation/Maintenance/Repair'), (5, 'Others'), (4, 'Insurance')], default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Manager'), (2, 'Employee'), (0, 'Organizer'), (3, 'Leader')], default=2),
        ),
    ]
