# Generated by Django 2.2 on 2019-06-09 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0021_auto_20190609_0954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='domain',
            field=models.PositiveSmallIntegerField(choices=[(2, 'Installation/Maintenance/Repair'), (5, 'Others'), (3, 'Rent-a-car/Ride sharing'), (1, 'Delivery Service'), (6, 'Sales(Pharma)'), (0, 'Sales'), (4, 'Insurance')], default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Manager'), (2, 'Employee'), (3, 'Leader'), (0, 'Organizer')], default=2),
        ),
    ]
