# Generated by Django 2.2 on 2019-07-04 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0023_auto_20190619_0449'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ping_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='domain',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Sales'), (1, 'Delivery Service'), (4, 'Insurance'), (5, 'Others'), (2, 'Installation/Maintenance/Repair'), (6, 'Sales(Pharma)'), (3, 'Rent-a-car/Ride sharing')], default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(3, 'Leader'), (0, 'Organizer'), (1, 'Manager'), (2, 'Employee')], default=2),
        ),
    ]
