# Generated by Django 2.2 on 2019-07-24 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0025_auto_20190717_1230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='domain',
            field=models.PositiveSmallIntegerField(choices=[(3, 'Rent-a-car/Ride sharing'), (5, 'Others'), (0, 'Sales'), (6, 'Sales(Pharma)'), (4, 'Insurance'), (2, 'Installation/Maintenance/Repair'), (1, 'Delivery Service')], default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(3, 'Leader'), (1, 'Manager'), (2, 'Employee'), (0, 'Organizer')], default=2),
        ),
    ]
