# Generated by Django 2.2 on 2019-06-09 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_appinfo_app_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appinfo',
            name='app_name',
            field=models.CharField(choices=[('manager', 'manager'), ('agent', 'agent')], default='manager', max_length=128),
        ),
    ]
