# Generated by Django 2.2 on 2019-04-07 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=16)),
                ('email', models.EmailField(max_length=254)),
                ('company_name', models.CharField(max_length=128)),
                ('employee_count', models.CharField(max_length=16)),
                ('domain_choice', models.CharField(max_length=255)),
                ('designation', models.CharField(max_length=128)),
            ],
        ),
    ]
