# Generated by Django 2.2 on 2019-04-07 03:10

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('text', models.CharField(blank=True, max_length=200)),
                ('type', models.PositiveSmallIntegerField(choices=[(7, 'Alert'), (3, 'Task postponed'), (8, 'Task started'), (5, 'New Task'), (0, 'Deadline crossed'), (2, 'Task cancelled'), (6, 'SOS'), (1, 'Unreachable'), (4, 'Near Deadline')], default=7)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('images', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('address', models.TextField(blank=True)),
                ('checked', models.BooleanField(default=False)),
            ],
        ),
    ]
