# Generated by Django 2.2 on 2019-04-07 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0003_auto_20190407_1007'),
        ('notification', '0002_auto_20190407_0310'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='assignment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='assignment.Assignment'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(12, 'New Comment'), (9, 'Task finished'), (5, 'New Task'), (11, 'Assignment Modified'), (6, 'SOS'), (7, 'Alert'), (0, 'Deadline crossed'), (1, 'Unreachable'), (10, 'Assignment Created'), (3, 'Task postponed'), (8, 'Task started'), (4, 'Near Deadline'), (2, 'Task cancelled')], default=7),
        ),
    ]
