# Generated by Django 2.2 on 2019-04-08 05:18

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0003_auto_20190407_1007'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='point',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(6, 'SOS'), (2, 'Task cancelled'), (8, 'Task started'), (5, 'New Task'), (7, 'Alert'), (12, 'New Comment'), (0, 'Deadline crossed'), (9, 'Task finished'), (1, 'Unreachable'), (10, 'Assignment Created'), (11, 'Assignment Modified'), (3, 'Task postponed'), (4, 'Near Deadline')], default=7),
        ),
    ]
