# Generated by Django 2.2 on 2019-04-08 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0004_auto_20190408_0518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(5, 'New Task'), (7, 'Alert'), (6, 'SOS'), (10, 'Assignment Created'), (8, 'Task started'), (0, 'Deadline crossed'), (1, 'Unreachable'), (4, 'Near Deadline'), (11, 'Assignment Modified'), (9, 'Task finished'), (2, 'Task cancelled'), (3, 'Task postponed'), (12, 'New Comment')], default=7),
        ),
    ]
