# Generated by Django 2.2 on 2019-04-08 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0005_auto_20190408_0646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(10, 'Assignment Created'), (12, 'New Comment'), (0, 'Deadline crossed'), (1, 'Unreachable'), (11, 'Assignment Modified'), (8, 'Task started'), (2, 'Task cancelled'), (3, 'Task postponed'), (4, 'Near Deadline'), (9, 'Task finished'), (6, 'SOS'), (5, 'New Task'), (7, 'Alert')], default=7),
        ),
    ]
