# Generated by Django 2.2 on 2019-04-11 09:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notification', '0006_auto_20190408_0925'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='recipient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_recipient', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Deadline crossed'), (4, 'Near Deadline'), (5, 'New Task'), (10, 'Assignment Created'), (12, 'New Comment'), (11, 'Assignment Modified'), (9, 'Task finished'), (2, 'Task cancelled'), (7, 'Alert'), (3, 'Task postponed'), (6, 'SOS'), (1, 'Unreachable'), (8, 'Task started')], default=7),
        ),
    ]
