# Generated by Django 2.2 on 2019-04-15 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0007_auto_20190411_0944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Deadline crossed'), (2, 'Task cancelled'), (6, 'SOS'), (11, 'Assignment Modified'), (7, 'Alert'), (8, 'Task started'), (4, 'Near Deadline'), (1, 'Unreachable'), (5, 'New Task'), (10, 'Assignment Created'), (3, 'Task postponed'), (9, 'Task finished'), (12, 'New Comment')], default=7),
        ),
    ]
