# Generated by Django 2.2 on 2019-04-23 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0008_auto_20190415_0641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Unreachable'), (11, 'Assignment Modified'), (12, 'New Comment'), (6, 'SOS'), (10, 'Assignment Created'), (2, 'Task cancelled'), (0, 'Deadline crossed'), (3, 'Task postponed'), (8, 'Task started'), (5, 'New Task'), (9, 'Task finished'), (7, 'Alert'), (4, 'Near Deadline')], default=7),
        ),
    ]
