# Generated by Django 2.2 on 2019-05-02 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0009_auto_20190423_0627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(12, 'New Comment'), (0, 'Deadline crossed'), (1, 'Unreachable'), (4, 'Near Deadline'), (2, 'Task cancelled'), (6, 'SOS'), (7, 'Alert'), (9, 'Task finished'), (5, 'New Task'), (3, 'Task postponed'), (11, 'Assignment Modified'), (8, 'Task started'), (10, 'Assignment Created')], default=7),
        ),
    ]
