# Generated by Django 2.2 on 2019-05-05 11:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0010_auto_20190502_0455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='timestamp',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(12, 'New Comment'), (4, 'Near Deadline'), (8, 'Task started'), (9, 'Task finished'), (10, 'Assignment Created'), (1, 'Unreachable'), (11, 'Assignment Modified'), (5, 'New Task'), (6, 'SOS'), (2, 'Task cancelled'), (7, 'Alert'), (0, 'Deadline crossed'), (3, 'Task postponed')], default=7),
        ),
    ]
