# Generated by Django 2.2 on 2019-05-05 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0011_auto_20190505_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(8, 'Task started'), (12, 'New Comment'), (0, 'Deadline crossed'), (11, 'Assignment Modified'), (9, 'Task finished'), (4, 'Near Deadline'), (7, 'Alert'), (3, 'Task postponed'), (5, 'New Task'), (2, 'Task cancelled'), (10, 'Assignment Created'), (6, 'SOS'), (1, 'Unreachable')], default=7),
        ),
    ]
