# Generated by Django 2.2 on 2019-05-13 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0012_auto_20190505_1213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(2, 'Task cancelled'), (12, 'New Comment'), (11, 'Assignment Modified'), (0, 'Deadline crossed'), (10, 'Assignment Created'), (1, 'Unreachable'), (9, 'Task finished'), (5, 'New Task'), (6, 'SOS'), (13, 'Force Offline'), (7, 'Alert'), (3, 'Task postponed'), (8, 'Task started'), (4, 'Near Deadline')], default=7),
        ),
    ]
