# Generated by Django 2.2 on 2019-05-16 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0013_auto_20190513_0517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(9, 'Task finished'), (3, 'Task postponed'), (4, 'Near Deadline'), (13, 'Force Offline'), (0, 'Deadline crossed'), (6, 'SOS'), (11, 'Assignment Modified'), (8, 'Task started'), (10, 'Assignment Created'), (5, 'New Task'), (12, 'New Comment'), (1, 'Unreachable'), (2, 'Task cancelled'), (7, 'Alert')], default=7),
        ),
    ]
