# Generated by Django 2.2 on 2019-05-20 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0014_auto_20190516_0613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(6, 'SOS'), (7, 'Alert'), (3, 'Task postponed'), (13, 'Force Offline'), (5, 'New Task'), (11, 'Assignment Modified'), (4, 'Near Deadline'), (10, 'Assignment Created'), (2, 'Task cancelled'), (1, 'Unreachable'), (0, 'Deadline crossed'), (9, 'Task finished'), (8, 'Task started'), (12, 'New Comment')], default=7),
        ),
    ]
