# Generated by Django 2.2 on 2019-05-22 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0015_auto_20190520_0822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(2, 'Task cancelled'), (6, 'SOS'), (1, 'Unreachable'), (5, 'New Task'), (12, 'New Comment'), (0, 'Deadline crossed'), (11, 'Assignment Modified'), (7, 'Alert'), (13, 'Force Offline'), (10, 'Assignment Created'), (4, 'Near Deadline'), (3, 'Task postponed'), (9, 'Task finished'), (8, 'Task started')], default=7),
        ),
    ]
