# Generated by Django 2.2 on 2019-05-25 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0017_auto_20190522_0934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Unreachable'), (10, 'Assignment Created'), (11, 'Assignment Modified'), (3, 'Task postponed'), (2, 'Task cancelled'), (8, 'Task started'), (4, 'Near Deadline'), (12, 'New Comment'), (7, 'Alert'), (13, 'Force Offline'), (6, 'SOS'), (0, 'Deadline crossed'), (9, 'Task finished'), (5, 'New Task')], default=7),
        ),
    ]
