# Generated by Django 2.2 on 2019-05-27 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0019_auto_20190525_0934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(7, 'Alert'), (10, 'Assignment Created'), (12, 'New Comment'), (11, 'Assignment Modified'), (1, 'Unreachable'), (9, 'Task finished'), (0, 'Deadline crossed'), (2, 'Task cancelled'), (5, 'New Task'), (3, 'Task postponed'), (6, 'SOS'), (4, 'Near Deadline'), (8, 'Task started'), (13, 'Force Offline')], default=7),
        ),
    ]
