# Generated by Django 2.2 on 2019-06-09 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0020_auto_20190527_0406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(7, 'Alert'), (12, 'New Comment'), (1, 'Unreachable'), (11, 'Assignment Modified'), (5, 'New Task'), (3, 'Task postponed'), (0, 'Deadline crossed'), (4, 'Near Deadline'), (8, 'Task started'), (2, 'Task cancelled'), (10, 'Assignment Created'), (13, 'Force Offline'), (9, 'Task finished'), (6, 'SOS')], default=7),
        ),
    ]
