# Generated by Django 2.2 on 2019-06-09 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0021_auto_20190609_0939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(10, 'Assignment Created'), (13, 'Force Offline'), (1, 'Unreachable'), (5, 'New Task'), (12, 'New Comment'), (11, 'Assignment Modified'), (6, 'SOS'), (4, 'Near Deadline'), (7, 'Alert'), (0, 'Deadline crossed'), (3, 'Task postponed'), (2, 'Task cancelled'), (9, 'Task finished'), (8, 'Task started')], default=7),
        ),
    ]
