# Generated by Django 2.2 on 2019-06-09 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0022_auto_20190609_0954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(3, 'Task postponed'), (4, 'Near Deadline'), (6, 'SOS'), (2, 'Task cancelled'), (10, 'Assignment Created'), (12, 'New Comment'), (7, 'Alert'), (8, 'Task started'), (5, 'New Task'), (13, 'Force Offline'), (1, 'Unreachable'), (0, 'Deadline crossed'), (11, 'Assignment Modified'), (9, 'Task finished')], default=7),
        ),
    ]
