# Generated by Django 2.2 on 2019-06-19 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0023_auto_20190609_1050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(2, 'Task cancelled'), (9, 'Task finished'), (10, 'Assignment Created'), (5, 'New Task'), (6, 'SOS'), (1, 'Unreachable'), (11, 'Assignment Modified'), (4, 'Near Deadline'), (0, 'Deadline crossed'), (12, 'New Comment'), (8, 'Task started'), (3, 'Task postponed'), (7, 'Alert'), (13, 'Force Offline')], default=7),
        ),
    ]
