# Generated by Django 2.2 on 2019-07-04 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0024_auto_20190619_0449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(5, 'New Task'), (2, 'Task cancelled'), (13, 'Force Offline'), (21, 'Ping Device'), (7, 'Alert'), (10, 'Assignment Created'), (11, 'Assignment Modified'), (3, 'Task postponed'), (8, 'Task started'), (9, 'Task finished'), (12, 'New Comment'), (4, 'Near Deadline'), (0, 'Deadline crossed'), (6, 'SOS'), (1, 'Unreachable')], default=7),
        ),
    ]
