# Generated by Django 2.2 on 2019-04-08 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0004_auto_20190408_0518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customersupport',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'In progress'), (0, 'Pending'), (2, 'Resolved')], default=0),
        ),
    ]
