# Generated by Django 2.2 on 2019-05-02 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0009_auto_20190423_0627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customersupport',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Pending'), (1, 'In progress'), (2, 'Resolved')], default=0),
        ),
    ]
