# Generated by Django 2.2 on 2019-05-13 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0012_auto_20190505_1213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customersupport',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'In progress'), (0, 'Pending'), (2, 'Resolved')], default=0),
        ),
    ]
