# Generated by Django 2.2 on 2019-05-20 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0014_auto_20190516_0613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customersupport',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'In progress'), (2, 'Resolved'), (0, 'Pending')], default=0),
        ),
    ]
