# Generated by Django 2.2 on 2019-04-07 03:10

import apps.assignment.config
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('description', models.CharField(blank=True, default='', max_length=512)),
                ('status', models.PositiveSmallIntegerField(blank=True, choices=[(4, 'Cancelled'), (3, 'Complete'), (1, 'Remaining'), (2, 'In progress')], default=1)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('deadline', models.DateTimeField(default=apps.assignment.config.default_deadline)),
                ('custom_fields', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True)),
                ('attachments', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('assignment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='assignment.Assignment')),
            ],
        ),
    ]
