# Generated by Django 2.2 on 2019-04-11 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0006_auto_20190408_0925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='status',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(3, 'Complete'), (2, 'In progress'), (1, 'Remaining'), (4, 'Cancelled')], default=1),
        ),
    ]
