# Generated by Django 2.2 on 2019-04-15 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0007_auto_20190411_0944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='status',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(2, 'In progress'), (4, 'Cancelled'), (3, 'Complete'), (1, 'Remaining')], default=1),
        ),
    ]
