# Generated by Django 2.2 on 2019-04-23 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0008_auto_20190415_0641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='status',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(4, 'Cancelled'), (2, 'In progress'), (1, 'Remaining'), (3, 'Complete')], default=1),
        ),
    ]
