# Generated by Django 2.2 on 2019-05-02 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0009_auto_20190423_0627'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='progress',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='status',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Remaining'), (4, 'Cancelled'), (2, 'In progress'), (3, 'Complete')], default=1),
        ),
    ]
