# Generated by Django 2.2 on 2019-05-05 12:13

import apps.assignment.config
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0011_auto_20190505_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='deadline',
            field=models.DateTimeField(db_index=True, default=apps.assignment.config.default_deadline),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='status',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Remaining'), (2, 'In progress'), (3, 'Complete'), (4, 'Cancelled')], default=1),
        ),
    ]
