# Generated by Django 2.2 on 2019-05-25 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0017_auto_20190522_0934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='status',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Remaining'), (2, 'In progress'), (3, 'Complete'), (4, 'Cancelled')], default=1),
        ),
    ]
