# Generated by Django 2.2 on 2019-06-19 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0021_auto_20190609_1050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='status',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(2, 'In progress'), (3, 'Complete'), (1, 'Remaining'), (4, 'Cancelled')], default=1),
        ),
    ]
