# Generated by Django 2.2 on 2019-07-17 12:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0023_auto_20190704_0508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='assignee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignment_assignee', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='status',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Remaining'), (2, 'In progress'), (3, 'Complete'), (4, 'Cancelled')], default=1),
        ),
    ]
