# Generated by Django 2.2 on 2019-04-07 03:10

import apps.org.config
import datetime
import django.contrib.postgres.fields
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oid', models.CharField(max_length=32, unique=True)),
                ('org_name', models.CharField(blank=True, max_length=128, null=True)),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'Enabled'), (0, 'Disabled'), (2, 'Suspended')], default=1)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('website', models.URLField(blank=True)),
                ('logo', models.URLField(blank=True, null=True)),
                ('day_start', models.TimeField(default=datetime.time(9, 0), null=True)),
                ('day_end', models.TimeField(default=datetime.time(17, 0), null=True)),
                ('location_interval', models.PositiveIntegerField(default=120, null=True)),
                ('org_set', models.BooleanField(default=False)),
                ('min_work_hour_p', models.PositiveIntegerField(blank=True, default=90)),
                ('min_task_hour_p', models.PositiveIntegerField(blank=True, default=50)),
                ('tracking_enabled', models.BooleanField(default=True)),
                ('weekend', django.contrib.postgres.fields.ArrayField(base_field=models.PositiveSmallIntegerField(choices=[(6, 'Sun'), (0, 'Mon'), (3, 'Thu'), (5, 'Sat'), (1, 'Tue'), (2, 'wed'), (4, 'Fri')]), blank=True, default=apps.org.config.default_weekend, size=None)),
            ],
        ),
    ]
