# Generated by Django 2.2 on 2019-04-07 10:07

import apps.org.config
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='weekend',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveSmallIntegerField(choices=[(1, 'Tue'), (0, 'Mon'), (2, 'wed'), (5, 'Sat'), (3, 'Thu'), (4, 'Fri'), (6, 'Sun')]), blank=True, default=apps.org.config.default_weekend, size=None),
        ),
    ]
