# Generated by Django 2.2 on 2019-04-08 05:18

import apps.org.config
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0002_auto_20190407_1007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='weekend',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveSmallIntegerField(choices=[(3, 'Thu'), (6, 'Sun'), (0, 'Mon'), (4, 'Fri'), (2, 'wed'), (1, 'Tue'), (5, 'Sat')]), blank=True, default=apps.org.config.default_weekend, size=None),
        ),
    ]
