# Generated by Django 2.2 on 2019-04-08 09:25

import apps.org.config
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0004_auto_20190408_0646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='weekend',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveSmallIntegerField(choices=[(1, 'Tue'), (2, 'wed'), (4, 'Fri'), (6, 'Sun'), (0, 'Mon'), (5, 'Sat'), (3, 'Thu')]), blank=True, default=apps.org.config.default_weekend, size=None),
        ),
    ]
