# Generated by Django 2.2 on 2019-04-11 09:44

import apps.org.config
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0005_auto_20190408_0925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='weekend',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveSmallIntegerField(choices=[(6, 'Sun'), (4, 'Fri'), (3, 'Thu'), (2, 'wed'), (0, 'Mon'), (5, 'Sat'), (1, 'Tue')]), blank=True, default=apps.org.config.default_weekend, size=None),
        ),
    ]
