# Generated by Django 2.2 on 2019-04-23 06:27

import apps.org.config
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0007_auto_20190415_0641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='weekend',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveSmallIntegerField(choices=[(2, 'wed'), (5, 'Sat'), (4, 'Fri'), (6, 'Sun'), (0, 'Mon'), (3, 'Thu'), (1, 'Tue')]), blank=True, default=apps.org.config.default_weekend, size=None),
        ),
    ]
