# Generated by Django 2.2 on 2019-05-02 04:55

import apps.org.config
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0008_auto_20190423_0627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='weekend',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveSmallIntegerField(choices=[(4, 'Fri'), (5, 'Sat'), (1, 'Tue'), (6, 'Sun'), (2, 'wed'), (0, 'Mon'), (3, 'Thu')]), blank=True, default=apps.org.config.default_weekend, size=None),
        ),
    ]
