# Generated by Django 2.2 on 2019-05-05 11:54

import apps.org.config
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0009_auto_20190502_0455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='weekend',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveSmallIntegerField(choices=[(0, 'Mon'), (5, 'Sat'), (6, 'Sun'), (1, 'Tue'), (2, 'wed'), (3, 'Thu'), (4, 'Fri')]), blank=True, default=apps.org.config.default_weekend, size=None),
        ),
    ]
