# Generated by Django 2.2 on 2019-05-05 12:13

import apps.org.config
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0010_auto_20190505_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='weekend',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveSmallIntegerField(choices=[(4, 'Fri'), (2, 'wed'), (0, 'Mon'), (3, 'Thu'), (6, 'Sun'), (1, 'Tue'), (5, 'Sat')]), blank=True, default=apps.org.config.default_weekend, size=None),
        ),
    ]
