# Generated by Django 2.2 on 2019-05-13 05:17

import apps.org.config
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0011_auto_20190505_1213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='weekend',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveSmallIntegerField(choices=[(3, 'Thu'), (1, 'Tue'), (6, 'Sun'), (0, 'Mon'), (4, 'Fri'), (5, 'Sat'), (2, 'wed')]), blank=True, default=apps.org.config.default_weekend, size=None),
        ),
    ]
