# Generated by Django 2.2 on 2019-05-16 06:13

import apps.org.config
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0012_auto_20190513_0517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='weekend',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveSmallIntegerField(choices=[(2, 'wed'), (6, 'Sun'), (0, 'Mon'), (1, 'Tue'), (3, 'Thu'), (4, 'Fri'), (5, 'Sat')]), blank=True, default=apps.org.config.default_weekend, size=None),
        ),
    ]
