# Generated by Django 2.2 on 2019-05-22 04:49

import apps.org.config
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0014_auto_20190520_0822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='weekend',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveSmallIntegerField(choices=[(6, 'Sun'), (2, 'wed'), (5, 'Sat'), (1, 'Tue'), (3, 'Thu'), (0, 'Mon'), (4, 'Fri')]), blank=True, default=apps.org.config.default_weekend, size=None),
        ),
    ]
