# Generated by Django 2.2 on 2019-05-22 09:34

import apps.org.config
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0015_auto_20190522_0449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='weekend',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveSmallIntegerField(choices=[(0, 'Mon'), (4, 'Fri'), (3, 'Thu'), (1, 'Tue'), (2, 'wed'), (6, 'Sun'), (5, 'Sat')]), blank=True, default=apps.org.config.default_weekend, size=None),
        ),
    ]
