# Generated by Django 2.2 on 2019-05-25 07:39

import apps.org.config
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0016_auto_20190522_0934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='weekend',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveSmallIntegerField(choices=[(5, 'Sat'), (2, 'wed'), (3, 'Thu'), (4, 'Fri'), (0, 'Mon'), (1, 'Tue'), (6, 'Sun')]), blank=True, default=apps.org.config.default_weekend, size=None),
        ),
    ]
