# Generated by Django 2.2 on 2019-05-25 09:34

import apps.org.config
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0017_auto_20190525_0739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='weekend',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveSmallIntegerField(choices=[(1, 'Tue'), (4, 'Fri'), (0, 'Mon'), (6, 'Sun'), (2, 'wed'), (3, 'Thu'), (5, 'Sat')]), blank=True, default=apps.org.config.default_weekend, size=None),
        ),
    ]
