# Generated by Django 2.2 on 2019-05-27 04:06

import apps.org.config
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0018_auto_20190525_0934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='weekend',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveSmallIntegerField(choices=[(6, 'Sun'), (1, 'Tue'), (4, 'Fri'), (0, 'Mon'), (5, 'Sat'), (3, 'Thu'), (2, 'wed')]), blank=True, default=apps.org.config.default_weekend, size=None),
        ),
    ]
