# Generated by Django 2.2 on 2019-06-09 09:54

import apps.org.config
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0020_auto_20190609_0939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='weekend',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveSmallIntegerField(choices=[(1, 'Tue'), (2, 'wed'), (6, 'Sun'), (5, 'Sat'), (4, 'Fri'), (0, 'Mon'), (3, 'Thu')]), blank=True, default=apps.org.config.default_weekend, size=None),
        ),
    ]
