# Generated by Django 2.2 on 2019-06-09 10:50

import apps.org.config
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0021_auto_20190609_0954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='weekend',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveSmallIntegerField(choices=[(3, 'Thu'), (0, 'Mon'), (4, 'Fri'), (5, 'Sat'), (1, 'Tue'), (2, 'wed'), (6, 'Sun')]), blank=True, default=apps.org.config.default_weekend, size=None),
        ),
    ]
