# Generated by Django 2.2 on 2019-06-19 04:49

import apps.org.config
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0022_auto_20190609_1050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='weekend',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveSmallIntegerField(choices=[(1, 'Tue'), (6, 'Sun'), (0, 'Mon'), (5, 'Sat'), (4, 'Fri'), (3, 'Thu'), (2, 'wed')]), blank=True, default=apps.org.config.default_weekend, size=None),
        ),
    ]
