# Generated by Django 2.2 on 2019-07-04 05:08

import apps.org.config
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0023_auto_20190619_0449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='weekend',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveSmallIntegerField(choices=[(1, 'Tue'), (6, 'Sun'), (5, 'Sat'), (2, 'wed'), (0, 'Mon'), (3, 'Thu'), (4, 'Fri')]), blank=True, default=apps.org.config.default_weekend, size=None),
        ),
    ]
