# Generated by Django 2.2 on 2019-07-17 12:30

import apps.org.config
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0024_auto_20190704_0508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='weekend',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveSmallIntegerField(choices=[(4, 'Fri'), (5, 'Sat'), (1, 'Tue'), (3, 'Thu'), (2, 'wed'), (0, 'Mon'), (6, 'Sun')]), blank=True, default=apps.org.config.default_weekend, size=None),
        ),
    ]
