# Generated by Django 2.2 on 2019-07-18 12:08

import apps.org.config
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0025_auto_20190717_1230'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reseller',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_name', models.CharField(max_length=128)),
                ('info', models.CharField(blank=True, max_length=255)),
                ('panel_link', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='organization',
            name='weekend',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveSmallIntegerField(choices=[(1, 'Tue'), (6, 'Sun'), (2, 'wed'), (3, 'Thu'), (0, 'Mon'), (4, 'Fri'), (5, 'Sat')]), blank=True, default=apps.org.config.default_weekend, size=None),
        ),
        migrations.AddField(
            model_name='organization',
            name='reseller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='org.Reseller'),
        ),
    ]
