# Generated by Django 2.2 on 2019-07-22 05:07

import apps.org.config
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0026_auto_20190718_1208'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reseller',
            old_name='org_name',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='organization',
            name='weekend',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveSmallIntegerField(choices=[(0, 'Mon'), (4, 'Fri'), (2, 'wed'), (5, 'Sat'), (3, 'Thu'), (1, 'Tue'), (6, 'Sun')]), blank=True, default=apps.org.config.default_weekend, size=None),
        ),
    ]
