# Generated by Django 2.2 on 2019-07-22 11:42

import apps.org.config
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0027_auto_20190722_0507'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='reseller',
        ),
        migrations.AddField(
            model_name='organization',
            name='has_reseller',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='organization',
            name='reseller_info',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='organization',
            name='reseller_name',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='organization',
            name='reseller_panel_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='weekend',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveSmallIntegerField(choices=[(0, 'Mon'), (3, 'Thu'), (2, 'wed'), (5, 'Sat'), (4, 'Fri'), (1, 'Tue'), (6, 'Sun')]), blank=True, default=apps.org.config.default_weekend, size=None),
        ),
    ]
