# Generated by Django 2.2 on 2019-07-24 06:54

import apps.org.config
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0028_auto_20190722_1142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='weekend',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveSmallIntegerField(choices=[(3, 'Thu'), (2, 'wed'), (4, 'Fri'), (5, 'Sat'), (6, 'Sun'), (0, 'Mon'), (1, 'Tue')]), blank=True, default=apps.org.config.default_weekend, size=None),
        ),
    ]
