# Generated by Django 2.2 on 2019-04-07 03:10

import datetime
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClientLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('address', models.CharField(blank=True, max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('date', models.DateField(default=datetime.date.today)),
                ('event', models.PositiveSmallIntegerField(choices=[(8, 'In OOC'), (3, 'To Offline'), (6, 'Finish task'), (2, 'No Task'), (1, 'On Task'), (4, 'To OOC'), (0, 'To Online'), (7, 'Off OOC'), (5, 'Start task')], default=2)),
                ('point', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
            ],
        ),
    ]
