# Generated by Django 2.2 on 2019-04-08 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0003_auto_20190407_1007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='event',
            field=models.PositiveSmallIntegerField(choices=[(4, 'To OOC'), (0, 'To Online'), (7, 'Off OOC'), (3, 'To Offline'), (6, 'Finish task'), (2, 'No Task'), (8, 'In OOC'), (5, 'Start task'), (1, 'On Task')], default=2),
        ),
    ]
