# Generated by Django 2.2 on 2019-04-08 06:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0004_auto_20190408_0646'),
        ('location', '0004_auto_20190408_0518'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='org',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='org.Organization'),
        ),
        migrations.AlterField(
            model_name='location',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='location',
            name='event',
            field=models.PositiveSmallIntegerField(choices=[(4, 'To OOC'), (1, 'On Task'), (3, 'To Offline'), (2, 'No Task'), (8, 'In OOC'), (0, 'To Online'), (7, 'Off OOC'), (6, 'Finish task'), (5, 'Start task')], default=2),
        ),
        migrations.AlterField(
            model_name='location',
            name='on_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='on_task', to='task.Task'),
        ),
    ]
