# Generated by Django 2.2 on 2019-04-11 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0006_auto_20190408_0925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='event',
            field=models.PositiveSmallIntegerField(choices=[(6, 'Finish task'), (5, 'Start task'), (0, 'To Online'), (1, 'On Task'), (3, 'To Offline'), (8, 'In OOC'), (4, 'To OOC'), (2, 'No Task'), (7, 'Off OOC')], default=2),
        ),
    ]
