# Generated by Django 2.2 on 2019-04-15 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0007_auto_20190411_0944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='event',
            field=models.PositiveSmallIntegerField(choices=[(2, 'No Task'), (3, 'To Offline'), (1, 'On Task'), (8, 'In OOC'), (7, 'Off OOC'), (4, 'To OOC'), (0, 'To Online'), (5, 'Start task'), (6, 'Finish task')], default=2),
        ),
    ]
