# Generated by Django 2.2 on 2019-04-23 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0008_auto_20190415_0641'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='address',
            field=models.CharField(blank=True, default='', max_length=512),
        ),
        migrations.AlterField(
            model_name='location',
            name='event',
            field=models.PositiveSmallIntegerField(choices=[(4, 'To OOC'), (1, 'On Task'), (6, 'Finish task'), (8, 'In OOC'), (2, 'No Task'), (0, 'To Online'), (5, 'Start task'), (3, 'To Offline'), (7, 'Off OOC')], default=2),
        ),
    ]
