# Generated by Django 2.2 on 2019-05-02 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0009_auto_20190423_0627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='event',
            field=models.PositiveSmallIntegerField(choices=[(1, 'On Task'), (4, 'To OOC'), (0, 'To Online'), (7, 'Off OOC'), (6, 'Finish task'), (5, 'Start task'), (2, 'No Task'), (3, 'To Offline'), (8, 'In OOC')], default=2),
        ),
    ]
