# Generated by Django 2.2 on 2019-05-05 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0011_auto_20190505_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='event',
            field=models.PositiveSmallIntegerField(choices=[(1, 'On Task'), (4, 'To OOC'), (7, 'Off OOC'), (0, 'To Online'), (6, 'Finish task'), (5, 'Start task'), (2, 'No Task'), (8, 'In OOC'), (3, 'To Offline')], default=2),
        ),
    ]
