# Generated by Django 2.2 on 2019-05-13 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0012_auto_20190505_1213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='event',
            field=models.PositiveSmallIntegerField(choices=[(4, 'To OOC'), (5, 'Start task'), (6, 'Finish task'), (3, 'To Offline'), (7, 'Off OOC'), (1, 'On Task'), (8, 'In OOC'), (0, 'To Online'), (2, 'No Task')], default=2),
        ),
    ]
