# Generated by Django 2.2 on 2019-05-16 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0013_auto_20190513_0517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='event',
            field=models.PositiveSmallIntegerField(choices=[(5, 'Start task'), (6, 'Finish task'), (8, 'In OOC'), (7, 'Off OOC'), (1, 'On Task'), (2, 'No Task'), (3, 'To Offline'), (0, 'To Online'), (4, 'To OOC')], default=2),
        ),
    ]
