# Generated by Django 2.2 on 2019-05-20 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0014_auto_20190516_0613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='event',
            field=models.PositiveSmallIntegerField(choices=[(5, 'Start task'), (0, 'To Online'), (6, 'Finish task'), (7, 'Off OOC'), (4, 'To OOC'), (3, 'To Offline'), (8, 'In OOC'), (1, 'On Task'), (2, 'No Task')], default=2),
        ),
    ]
