# Generated by Django 2.2 on 2019-05-22 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0015_auto_20190520_0822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='event',
            field=models.PositiveSmallIntegerField(choices=[(6, 'Finish task'), (1, 'On Task'), (4, 'To OOC'), (7, 'Off OOC'), (8, 'In OOC'), (5, 'Start task'), (0, 'To Online'), (2, 'No Task'), (3, 'To Offline')], default=2),
        ),
    ]
