# Generated by Django 2.2 on 2019-05-22 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0016_auto_20190522_0449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='event',
            field=models.PositiveSmallIntegerField(choices=[(2, 'No Task'), (4, 'To OOC'), (0, 'To Online'), (1, 'On Task'), (3, 'To Offline'), (7, 'Off OOC'), (8, 'In OOC'), (6, 'Finish task'), (5, 'Start task')], default=2),
        ),
    ]
