# Generated by Django 2.2 on 2019-05-25 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0017_auto_20190522_0934'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='mac',
            field=models.CharField(blank=True, default='', max_length=16),
        ),
        migrations.AlterField(
            model_name='location',
            name='event',
            field=models.PositiveSmallIntegerField(choices=[(6, 'Finish task'), (5, 'Start task'), (0, 'To Online'), (4, 'To OOC'), (1, 'On Task'), (8, 'In OOC'), (3, 'To Offline'), (7, 'Off OOC'), (2, 'No Task')], default=2),
        ),
    ]
