# Generated by Django 2.2 on 2019-05-25 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0018_auto_20190525_0739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='event',
            field=models.PositiveSmallIntegerField(choices=[(5, 'Start task'), (6, 'Finish task'), (7, 'Off OOC'), (8, 'In OOC'), (3, 'To Offline'), (2, 'No Task'), (4, 'To OOC'), (1, 'On Task'), (0, 'To Online')], default=2),
        ),
    ]
