# Generated by Django 2.2 on 2019-05-27 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0019_auto_20190525_0934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='event',
            field=models.PositiveSmallIntegerField(choices=[(6, 'Finish task'), (7, 'Off OOC'), (5, 'Start task'), (8, 'In OOC'), (0, 'To Online'), (1, 'On Task'), (3, 'To Offline'), (2, 'No Task'), (4, 'To OOC')], default=2),
        ),
        migrations.AlterField(
            model_name='location',
            name='mac',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
