# Generated by Django 2.2 on 2019-06-09 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0020_auto_20190527_0406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='event',
            field=models.PositiveSmallIntegerField(choices=[(3, 'To Offline'), (7, 'Off OOC'), (8, 'In OOC'), (6, 'Finish task'), (0, 'To Online'), (2, 'No Task'), (4, 'To OOC'), (1, 'On Task'), (5, 'Start task')], default=2),
        ),
    ]
