# Generated by Django 2.2 on 2019-06-09 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0021_auto_20190609_0939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='event',
            field=models.PositiveSmallIntegerField(choices=[(5, 'Start task'), (2, 'No Task'), (3, 'To Offline'), (6, 'Finish task'), (7, 'Off OOC'), (4, 'To OOC'), (1, 'On Task'), (8, 'In OOC'), (0, 'To Online')], default=2),
        ),
    ]
