# Generated by Django 2.2 on 2019-06-09 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0022_auto_20190609_0954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='event',
            field=models.PositiveSmallIntegerField(choices=[(3, 'To Offline'), (4, 'To OOC'), (6, 'Finish task'), (1, 'On Task'), (5, 'Start task'), (0, 'To Online'), (7, 'Off OOC'), (2, 'No Task'), (8, 'In OOC')], default=2),
        ),
    ]
