# Generated by Django 2.2 on 2019-06-19 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0023_auto_20190609_1050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='event',
            field=models.PositiveSmallIntegerField(choices=[(2, 'No Task'), (6, 'Finish task'), (5, 'Start task'), (8, 'In OOC'), (0, 'To Online'), (7, 'Off OOC'), (4, 'To OOC'), (1, 'On Task'), (3, 'To Offline')], default=2),
        ),
    ]
