# Generated by Django 2.2 on 2019-07-17 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0025_auto_20190704_0508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='event',
            field=models.PositiveSmallIntegerField(choices=[(5, 'Start task'), (7, 'Off OOC'), (1, 'On Task'), (0, 'To Online'), (6, 'Finish task'), (8, 'In OOC'), (21, 'Ping Server'), (3, 'To Offline'), (4, 'To OOC'), (2, 'No Task')], default=2),
        ),
    ]
