# Generated by Django 2.2 on 2019-07-24 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0026_auto_20190717_1230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='event',
            field=models.PositiveSmallIntegerField(choices=[(6, 'Finish task'), (2, 'No Task'), (1, 'On Task'), (8, 'In OOC'), (0, 'To Online'), (7, 'Off OOC'), (4, 'To OOC'), (21, 'Ping Server'), (3, 'To Offline'), (5, 'Start task')], default=2),
        ),
    ]
