# Generated by Django 2.2 on 2019-04-11 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0004_auto_20190408_0646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Private'), (2, 'Broadcast'), (1, 'Group')], default=0),
        ),
    ]
