# Generated by Django 2.2 on 2019-05-20 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0011_auto_20190516_0613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(2, 'Broadcast'), (1, 'Group'), (0, 'Private')], default=0),
        ),
    ]
