# Generated by Django 2.2 on 2019-05-25 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0014_auto_20190522_0934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Group'), (2, 'Broadcast'), (0, 'Private')], default=0),
        ),
    ]
