# Generated by Django 2.2 on 2019-05-25 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0015_auto_20190525_0739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Private'), (2, 'Broadcast'), (1, 'Group')], default=0),
        ),
    ]
