# Generated by Django 2.2 on 2019-07-17 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0020_auto_20190619_0449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Group'), (0, 'Private'), (2, 'Broadcast')], default=0),
        ),
        migrations.AlterField(
            model_name='thread',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Group'), (0, 'Private'), (2, 'Broadcast')], default=0),
        ),
    ]
