# Generated by Django 2.2 on 2019-07-24 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0021_auto_20190717_1230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Group'), (2, 'Broadcast'), (0, 'Private')], default=0),
        ),
        migrations.AlterField(
            model_name='thread',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Group'), (2, 'Broadcast'), (0, 'Private')], default=0),
        ),
    ]
